add categories component
Czaroos/flashcards-frontend pull request #24
Opened 2020-11-19 13:49 UTC by ajronn

2020-11-20 08:30 UTC, i0skar approved these changes

2020-11-20 08:35 UTC, Czaroos requested changes
Try to add it to our category dashboard as well and lets transform this to user actions sidebar only since we have separate dashboard for categories. Overall though good job

2020-11-20 08:35 UTC, Czaroos commented on src/components/categories/index.tsx
> +            <Arrow>
Make arrow pointing different directions when collapsing/expanding sidebar

2020-11-20 08:35 UTC, Czaroos commented on src/modules/dashboard/index.tsx
> +  const [categories, setCategories] = useState<CategoriesItem[]>([]);
this is not needed since we have seperate dashboard for categories, let's make this component a sidebar for user actions

2020-11-20 08:35 UTC, Czaroos commented on stories/Categories.stories.tsx
> +const categories: CategoriesItem[] = [
same here

2020-11-23 14:53 UTC, i0skar approved these changes

2020-12-01 10:42 UTC, closed without merging